name: final_project_flutter
description: "Final Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_localizations:
    sdk: flutter

  sqflite: ^2.0.0+4
  path_provider: ^2.0.9
  provider: ^6.0.3
  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.15
  flutter_svg: ^0.22.0
  encrypted_shared_preferences: ^3.0.1
  url_launcher: ^6.3.0
  floor: ^1.2.0
  path: ^1.8.0
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.7
  floor_generator: ^1.2.0
  json_serializable: ^6.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/translations/de.json
    - assets/translations/en.json